package thinkinginjava.chapter02.exercise13;

/*
 * Chapter 2. Exercise 13. Difficult - 1/10.
 *
 * Run Documentation1.java, Documentation2.java, and Documentation3.java through Javadoc. Verify the resulting
 * documentation with your Web browser.
 */

/**
 * A class comment
 */
public class Documentation1 {

    /**
     * A field comment
     */
    public int i;

    /**
     * A method comment
     */
    public void f() {
    }
}

/*
 * Run:
 *
 * $ javadoc -d doc ./*
 * Loading source file .\Documentation1.java...
 * Loading source file .\Documentation2.java...
 * Loading source file .\Documentation3.java...
 * Constructing Javadoc information...
 * Creating destination directory: "doc\"
 * Standard Doclet version 1.8.0_102
 * Building tree for all the packages and classes...
 * Generating doc\thinkinginjava\chapter02\exercise13\Documentation1.html...
 * Generating doc\thinkinginjava\chapter02\exercise13\Documentation2.html...
 * Generating doc\thinkinginjava\chapter02\exercise13\Documentation3.html...
 * Generating doc\thinkinginjava\chapter02\exercise13\package-frame.html...
 * Generating doc\thinkinginjava\chapter02\exercise13\package-summary.html...
 * Generating doc\thinkinginjava\chapter02\exercise13\package-tree.html...
 * Generating doc\constant-values.html...
 * Building index for all the packages and classes...
 * Generating doc\overview-tree.html...
 * Generating doc\index-all.html...
 * Generating doc\deprecated-list.html...
 * Building index for all classes...
 * Generating doc\allclasses-frame.html...
 * Generating doc\allclasses-noframe.html...
 * Generating doc\index.html...
 * Generating doc\help-doc.html...
 *
 * $
 *
 */